### PR TITLE
no r.result available

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by rokusottervanger** [comment]
In which practical cases is `r == ""` true? I can't reproduce this in simulation.

**Comment by MatthijsBurgh** [comment]
I don't know if it is possible. But in case it happens, this is the desired behavior. Therefore I suggest to keep it in for now. Let's decide after tue-robotics/hmi#13 is solved. Because right now there is no return in case nothing is heard.

**Comment by Rayman** [comment]
This can't happen.

When the speech bug happens tue-robotics/dragonfly_speech_recognition#14, `r.result == previous result`

**Comment by rokusottervanger** [comment]
So suggestion is to completely remove the check for r.result == "", right, @Rayman? (`r` is a string, so there is no `result` field anyway.) In a new PR, to keep the history clean.

**Comment by Rayman** [comment]
The API should be used like this:
```py
try:
    sentence = hmi.query('', 'T -> yes | no', 'T').sentence
except TimeoutException:
    do_something_if_timeout_happened()
else:
    # no exception, so we have a sentence
    if sentence == 'yes':
        ....
```

**Pull request closed without merging**
