### PR TITLE
RWC2018

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by rokusottervanger** [comment]
I had no part in this, but it looks good to me. If it works, I say go. I didn't test, so I'm not approving for the time being.

**Comment by MatthijsBurgh** [comment]
I don't agree that people detector etc is in a rgbd_to_ros launch file.

**Comment by rokusottervanger** [comment]
@matthijsburgh It looks to me as if this was already like this before these changes, right?

**Comment by MatthijsBurgh** [comment]
Indeed it was. So that should be in a refactor branch

**Comment by MatthijsBurgh** [comment]
I approve

**Review by LoyVanBeek — APPROVED** [review]

**Pull request merged**
